package view;

import control.OrdenacaoControle;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import model.FileChooser;
import model.Fiscalizacao;
import model.FiscalizacaoTableModel;
import sort.Ordenacao;

// @author Anpix
public class frmOrdenacao extends javax.swing.JFrame {

    private OrdenacaoControle ordenacaoControle = null;
    private List<Fiscalizacao> fiscalizacaoList = Collections.emptyList();

    // Creates new form frmOrdenacao
    public frmOrdenacao() {
        initComponents();
        setResizable(false);
        ordenacaoControle = new OrdenacaoControle();
    }

    private void Clean() {
        //Limpa txt campos
        txtFile.setText("");
        txtInsertion.setText("");
        txtMerge.setText("");
        txtSelection.setText("");
        txtBubble.setText("");
        txtQuick.setText("");
        fiscalizacaoList = null;

        //Define novo modelo vazio
        FiscalizacaoTableModel fiscalizacaoTableModel = new FiscalizacaoTableModel(Collections.emptyList());

        //Atribui o modelo vazio às tabelas
        tblDados.setModel(fiscalizacaoTableModel);
        tblSelection.setModel(fiscalizacaoTableModel);
        tblInsertion.setModel(fiscalizacaoTableModel);
        tblBubble.setModel(fiscalizacaoTableModel);
        tblMerge.setModel(fiscalizacaoTableModel);
        tblQuick.setModel(fiscalizacaoTableModel);
    }

    public void showData(List<Fiscalizacao> fiscalizacaoList) {
        this.fiscalizacaoList = fiscalizacaoList;
        FiscalizacaoTableModel fiscalizacaoTableModel = new FiscalizacaoTableModel(fiscalizacaoList);
        tblDados.setModel(fiscalizacaoTableModel);
    }

    public void ordenadoSelectionSort(List<Fiscalizacao> listaOrdenada) {
        tblSelection.setModel(new FiscalizacaoTableModel(listaOrdenada));
    }

    public void ordenadoInsertionSort(List<Fiscalizacao> listaOrdenada) {
        tblInsertion.setModel(new FiscalizacaoTableModel(listaOrdenada));
    }

    public void ordenadoBubbleSort(List<Fiscalizacao> listaOrdenada) {
        tblBubble.setModel(new FiscalizacaoTableModel(listaOrdenada));
    }

    public void ordenadoMergeSort(List<Fiscalizacao> listaOrdenada) {
        tblMerge.setModel(new FiscalizacaoTableModel(listaOrdenada));
    }

    public void ordenadoQuickSort(List<Fiscalizacao> listaOrdenada) {
        tblQuick.setModel(new FiscalizacaoTableModel(listaOrdenada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labSelection = new javax.swing.JLabel();
        labInsertion = new javax.swing.JLabel();
        labBubble = new javax.swing.JLabel();
        labMerge = new javax.swing.JLabel();
        labQuick = new javax.swing.JLabel();
        txtSelection = new javax.swing.JTextField();
        txtInsertion = new javax.swing.JTextField();
        txtBubble = new javax.swing.JTextField();
        txtMerge = new javax.swing.JTextField();
        txtQuick = new javax.swing.JTextField();
        butSelection = new javax.swing.JButton();
        butInsertion = new javax.swing.JButton();
        butBubble = new javax.swing.JButton();
        butMerge = new javax.swing.JButton();
        butQuick = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        butClean = new javax.swing.JButton();
        butOrder = new javax.swing.JButton();
        butFile = new javax.swing.JButton();
        butReload = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSelection = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInsertion = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBubble = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMerge = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblQuick = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTitle.setText("Algoritmos de Ordenação");

        labSelection.setText("SelectionSort");

        labInsertion.setText("InsertionSort");

        labBubble.setText("BubbleSort");

        labMerge.setText("MergeSort");

        labQuick.setText("QuickSort");

        txtInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertionActionPerformed(evt);
            }
        });

        butSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lightning.png"))); // NOI18N
        butSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSelectionActionPerformed(evt);
            }
        });

        butInsertion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lightning.png"))); // NOI18N
        butInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertionActionPerformed(evt);
            }
        });

        butBubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lightning.png"))); // NOI18N
        butBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBubbleActionPerformed(evt);
            }
        });

        butMerge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lightning.png"))); // NOI18N
        butMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMergeActionPerformed(evt);
            }
        });

        butQuick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lightning.png"))); // NOI18N
        butQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butQuickActionPerformed(evt);
            }
        });

        jLabel1.setText("HH:mm:ss.SSS");

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDados);

        jLabel2.setText("Arquivo:");

        butClean.setText("Limpar");
        butClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCleanActionPerformed(evt);
            }
        });

        butOrder.setText("Ordenar");
        butOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOrderActionPerformed(evt);
            }
        });

        butFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/search-icon.png"))); // NOI18N
        butFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFileActionPerformed(evt);
            }
        });

        butReload.setText("Reload");
        butReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labBubble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labMerge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labQuick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSelection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBubble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butQuick)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(butSelection)
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(butInsertion)
                                            .addComponent(butBubble)
                                            .addComponent(butMerge))
                                        .addGap(125, 125, 125)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(butReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(butClean)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(butOrder)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(butFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBubble, txtInsertion, txtMerge, txtQuick, txtSelection});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitle)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labSelection)
                            .addComponent(txtSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butSelection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labInsertion)
                            .addComponent(txtInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butInsertion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labBubble)
                            .addComponent(txtBubble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butBubble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labMerge)
                            .addComponent(txtMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butMerge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labQuick)
                            .addComponent(butQuick)
                            .addComponent(txtQuick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butOrder)
                            .addComponent(butClean)
                            .addComponent(butReload))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Algoritmo", jPanel1);

        tblSelection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSelection);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Selection", jPanel2);

        tblInsertion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblInsertion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Insertion", jPanel3);

        tblBubble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblBubble);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Bubble", jPanel4);

        tblMerge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblMerge);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Merge", jPanel5);

        tblQuick.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Ano", "Mês", "Empregador", "Logradouro", "Município", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblQuick);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Quick", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertionActionPerformed

    private void butCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCleanActionPerformed
        Clean();
    }//GEN-LAST:event_butCleanActionPerformed

    private void butOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOrderActionPerformed
        try {
            Ordenacao selectionSort = ordenacaoControle.ordenarSelectionSort(fiscalizacaoList);
            Ordenacao insertionSort = ordenacaoControle.ordenarInsertionSort(fiscalizacaoList);
            Ordenacao bubbleSort = ordenacaoControle.ordenarBubbleSort(fiscalizacaoList);
            Ordenacao mergeSort = ordenacaoControle.ordenarMergeSort(fiscalizacaoList);
            Ordenacao quickSort = ordenacaoControle.ordenarQuickSort(fiscalizacaoList);
            
            //
            ordenadoSelectionSort(selectionSort.listaOrdenada());
            ordenadoInsertionSort(insertionSort.listaOrdenada());
            ordenadoBubbleSort(bubbleSort.listaOrdenada());
            ordenadoMergeSort(mergeSort.listaOrdenada());
            ordenadoQuickSort(quickSort.listaOrdenada());
            
            //Mostra tempo
            txtSelection.setText(selectionSort.tempoDeOrdenacao());
            txtInsertion.setText(insertionSort.tempoDeOrdenacao());
            txtBubble.setText(bubbleSort.tempoDeOrdenacao());
            txtMerge.setText(mergeSort.tempoDeOrdenacao());
            txtQuick.setText(mergeSort.tempoDeOrdenacao());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_butOrderActionPerformed

    private void butFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFileActionPerformed
        FileChooser fc = new FileChooser();
        fc.open();
        txtFile.setText(fc.getEndereco());
        fiscalizacaoList = ordenacaoControle.loadFile(fc.getEndereco());
        showData(fiscalizacaoList);
    }//GEN-LAST:event_butFileActionPerformed

    private void butSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSelectionActionPerformed
        try {
            Ordenacao lista = ordenacaoControle.ordenarSelectionSort(fiscalizacaoList);
            ordenadoSelectionSort(lista.listaOrdenada());
            txtSelection.setText(lista.tempoDeOrdenacao());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_butSelectionActionPerformed

    private void butInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertionActionPerformed
        try {
            Ordenacao lista = ordenacaoControle.ordenarInsertionSort(fiscalizacaoList);
            ordenadoInsertionSort(lista.listaOrdenada());
            txtInsertion.setText(lista.tempoDeOrdenacao());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_butInsertionActionPerformed

    private void butBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBubbleActionPerformed
        try{
            Ordenacao lista = ordenacaoControle.ordenarBubbleSort(fiscalizacaoList);
            ordenadoBubbleSort(lista.listaOrdenada());
            txtBubble.setText(lista.tempoDeOrdenacao());
        } catch (Exception e){
        
        }
    }//GEN-LAST:event_butBubbleActionPerformed

    private void butMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMergeActionPerformed
        Ordenacao lista = ordenacaoControle.ordenarMergeSort(fiscalizacaoList);
        ordenadoMergeSort(lista.listaOrdenada());
        txtMerge.setText(lista.tempoDeOrdenacao());
    }//GEN-LAST:event_butMergeActionPerformed

    private void butQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butQuickActionPerformed
        Ordenacao lista = ordenacaoControle.ordenarQuickSort(fiscalizacaoList);
        ordenadoQuickSort(lista.listaOrdenada());
        txtQuick.setText(lista.tempoDeOrdenacao());
    }//GEN-LAST:event_butQuickActionPerformed

    private void butReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReloadActionPerformed
        fiscalizacaoList = ordenacaoControle.loadFile(txtFile.getText());
        showData(fiscalizacaoList);
    }//GEN-LAST:event_butReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrdenacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrdenacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrdenacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrdenacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrdenacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBubble;
    private javax.swing.JButton butClean;
    private javax.swing.JButton butFile;
    private javax.swing.JButton butInsertion;
    private javax.swing.JButton butMerge;
    private javax.swing.JButton butOrder;
    private javax.swing.JButton butQuick;
    private javax.swing.JButton butReload;
    private javax.swing.JButton butSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labBubble;
    private javax.swing.JLabel labInsertion;
    private javax.swing.JLabel labMerge;
    private javax.swing.JLabel labQuick;
    private javax.swing.JLabel labSelection;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTable tblBubble;
    private javax.swing.JTable tblDados;
    private javax.swing.JTable tblInsertion;
    private javax.swing.JTable tblMerge;
    private javax.swing.JTable tblQuick;
    private javax.swing.JTable tblSelection;
    private javax.swing.JTextField txtBubble;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtInsertion;
    private javax.swing.JTextField txtMerge;
    private javax.swing.JTextField txtQuick;
    private javax.swing.JTextField txtSelection;
    // End of variables declaration//GEN-END:variables
}
